import type { LookupResult, TranscriptItem } from "../contract.js";
import { escapeHtml } from "./escape.js";
import { STYLE } from "./style.js";

export interface Rendered {
  status: number;
  html: string;
}

const SITE = "Transcript";

function document_(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="robots" content="noindex">
<style>${STYLE}</style>
</head>
<body>
<div class="wrap">
${body}
<footer>${SITE}. Captions only. This page reads the captions a video already carries. It does not listen to audio.</footer>
</div>
</body>
</html>`;
}

function readable(when: string): string {
  const at = new Date(when);
  if (Number.isNaN(at.getTime())) return when;
  return at.toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

function whoWroteIt(kind: string): string {
  if (kind === "asr") return "generated by machine";
  if (kind === "standard") return "written by a person";
  return "unknown";
}

// Long text is hard to read as one block, so the segments are gathered into paragraphs of roughly
// this many characters. The captions carry no paragraph of their own.
const PARAGRAPH_CHARS = 700;

export function paragraphsOf(item: TranscriptItem): string[] {
  const paragraphs: string[] = [];
  let current = "";
  for (const segment of item.segments) {
    current = current ? `${current} ${segment.text}` : segment.text;
    if (current.length >= PARAGRAPH_CHARS) {
      paragraphs.push(current);
      current = "";
    }
  }
  if (current) paragraphs.push(current);
  if (paragraphs.length === 0 && item.text) paragraphs.push(item.text);
  return paragraphs;
}

function header(item: TranscriptItem): string {
  const meta = [
    `<li>Video <b>${escapeHtml(item.video_id)}</b></li>`,
    item.has_captions ? `<li>Captions <b>${escapeHtml(whoWroteIt(item.track_kind))}</b></li>` : "",
    item.has_captions && item.track_name ? `<li>Track <b>${escapeHtml(item.track_name)}</b></li>` : "",
    `<li>Read <b>${escapeHtml(readable(item.fetched_at))}</b></li>`,
  ]
    .filter(Boolean)
    .join("\n    ");
  return `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>${escapeHtml(item.title)}</h1>
  <ul class="meta">
    ${meta}
  </ul>
</header>`;
}

function transcriptPage(item: TranscriptItem): Rendered {
  const body = paragraphsOf(item)
    .map((p) => `<p>${escapeHtml(p)}</p>`)
    .join("\n  ");
  return {
    status: 200,
    html: document_(item.title, `${header(item)}
<article class="transcript">
  ${body}
</article>
<p class="note"><span>Source: ${escapeHtml(item.source)}</span></p>`),
  };
}

function noCaptionsPage(item: TranscriptItem): Rendered {
  return {
    status: 200,
    html: document_(item.title, `${header(item)}
<div class="note">
  <h2>This video has no captions</h2>
  <p>There is nothing to read. The video carries no caption track, so there is no text to show.</p>
  <p>This page reads captions only. It does not listen to the audio and it does not write text from
  speech. If somebody adds captions to the video later, come back and the text will be here.</p>
</div>`),
  };
}

function problemPage(status: number, title: string, lines: string[]): Rendered {
  const body = lines.map((l) => `  <p>${l}</p>`).join("\n");
  return {
    status,
    html: document_(title, `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>${escapeHtml(title)}</h1>
</header>
<div class="note">
${body}
</div>
<form action="/videos" method="get">
  <label for="id">Try another video id</label>
  <input type="text" id="id" name="id" inputmode="latin" autocomplete="off"
         placeholder="gyN9lV9QgyA" pattern="[A-Za-z0-9_-]{11}" required>
  <button type="submit">Read it</button>
</form>`),
  };
}

export function renderPage(result: LookupResult): Rendered {
  switch (result.kind) {
    case "ok":
      return result.item.has_captions ? transcriptPage(result.item) : noCaptionsPage(result.item);
    case "bad_id":
      return problemPage(400, "That is not a video id", [
        `A video id is eleven characters, for example <code>gyN9lV9QgyA</code>. This page was given
         <code>${escapeHtml(result.given.slice(0, 40))}</code>, which is not one.`,
        `Take the id from the address of the video. In
         <code>youtube.com/watch?v=gyN9lV9QgyA</code> the id is the part after <code>v=</code>.`,
      ]);
    case "not_found":
      return problemPage(404, "No video with that id", [
        `The id <code>${escapeHtml(result.video_id)}</code> has the right shape, but the platform
         holds no video under it.`,
        `The video may be private, it may be deleted, or the id may have one character wrong.`,
      ]);
    case "upstream_failed":
      return problemPage(502, "The platform did not answer", [
        `The text of <code>${escapeHtml(result.video_id)}</code> could not be read just now.`,
        `Nothing was stored, so trying again in a minute is worth doing.`,
        `What went wrong: ${escapeHtml(result.reason)}.`,
      ]);
  }
}

export function renderIndex(): Rendered {
  return {
    status: 200,
    html: document_(`${SITE}: read a video as text`, `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>Read a video as text</h1>
</header>
<div class="note">
  <h2>How it works</h2>
  <p>Give this page a video id and it shows the captions that video already carries, as text you can
  read, search and send to somebody. A transcript is a link.</p>
  <p>The address is <code>/videos?id=&lt;video id&gt;</code>, for example
  <a href="/videos?id=gyN9lV9QgyA">/videos?id=gyN9lV9QgyA</a>.</p>
  <p>Captions only. A video with no captions gets a page that says so.</p>
</div>
<form action="/videos" method="get">
  <label for="id">Video id, eleven characters</label>
  <input type="text" id="id" name="id" inputmode="latin" autocomplete="off"
         placeholder="gyN9lV9QgyA" pattern="[A-Za-z0-9_-]{11}" required>
  <button type="submit">Read it</button>
</form>`),
  };
}

export function renderUnknownRoute(): Rendered {
  return problemPage(404, "There is nothing here", [
    `This page serves one address: <code>/videos?id=&lt;video id&gt;</code>.`,
    `Go to <a href="/">the front page</a> to start from there.`,
  ]);
}
