import type { Cause, LookupResult, TranscriptItem } from "../contract.js";
import { escapeHtml } from "./escape.js";
import { STYLE } from "./style.js";

export interface Rendered {
  status: number;
  html: string;
}

const SITE = "Transcript";

function document_(title: string, body: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(title)}</title>
<meta name="robots" content="noindex">
<style>${STYLE}</style>
</head>
<body>
<div class="wrap">
${body}
<footer>${SITE}. Captions only. This page reads the captions a video already carries. It does not listen to audio.</footer>
</div>
</body>
</html>`;
}

function readable(when: string): string {
  const at = new Date(when);
  if (Number.isNaN(at.getTime())) return when;
  return at.toISOString().replace("T", " ").slice(0, 16) + " UTC";
}

function whoWroteIt(kind: string): string {
  if (kind === "asr") return "generated by machine";
  if (kind === "standard") return "written by a person";
  return "unknown";
}

// Long text is hard to read as one block, so the segments are gathered into paragraphs of roughly
// this many characters. The captions carry no paragraph of their own.
const PARAGRAPH_CHARS = 700;

export function paragraphsOf(item: TranscriptItem): string[] {
  const paragraphs: string[] = [];
  let current = "";
  for (const segment of item.segments) {
    current = current ? `${current} ${segment.text}` : segment.text;
    if (current.length >= PARAGRAPH_CHARS) {
      paragraphs.push(current);
      current = "";
    }
  }
  if (current) paragraphs.push(current);
  if (paragraphs.length === 0 && item.text) paragraphs.push(item.text);
  return paragraphs;
}

function header(item: TranscriptItem): string {
  const meta = [
    `<li>Video <b>${escapeHtml(item.video_id)}</b></li>`,
    item.has_captions ? `<li>Captions <b>${escapeHtml(whoWroteIt(item.track_kind))}</b></li>` : "",
    item.has_captions && item.track_name ? `<li>Track <b>${escapeHtml(item.track_name)}</b></li>` : "",
    `<li>Read <b>${escapeHtml(readable(item.fetched_at))}</b></li>`,
  ]
    .filter(Boolean)
    .join("\n    ");
  return `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>${escapeHtml(item.title)}</h1>
  <ul class="meta">
    ${meta}
  </ul>
</header>`;
}

function transcriptPage(item: TranscriptItem): Rendered {
  const body = paragraphsOf(item)
    .map((p) => `<p>${escapeHtml(p)}</p>`)
    .join("\n  ");
  return {
    status: 200,
    html: document_(item.title, `${header(item)}
<article class="transcript">
  ${body}
</article>
<p class="note"><span>Source: ${escapeHtml(item.source)}</span></p>`),
  };
}

function noCaptionsPage(item: TranscriptItem): Rendered {
  return {
    status: 200,
    html: document_(item.title, `${header(item)}
<div class="note">
  <h2>This video has no captions</h2>
  <p>There is nothing to read. The video carries no caption track, so there is no text to show.</p>
  <p>This page reads captions only. It does not listen to the audio and it does not write text from
  speech. If somebody adds captions to the video later, come back and the text will be here.</p>
</div>`),
  };
}

function problemPage(status: number, title: string, lines: string[]): Rendered {
  const body = lines.map((l) => `  <p>${l}</p>`).join("\n");
  return {
    status,
    html: document_(title, `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>${escapeHtml(title)}</h1>
</header>
<div class="note">
${body}
</div>
<form action="/videos" method="get">
  <label for="id">Try another video id</label>
  <input type="text" id="id" name="id" inputmode="latin" autocomplete="off"
         placeholder="gyN9lV9QgyA" pattern="[A-Za-z0-9_-]{11}" required>
  <button type="submit">Read it</button>
</form>`),
  };
}


// One page per cause. A refusal is not a missing video, so none of these answers 404, and none of
// them tells the reader to try again when trying again cannot work.
//
// Every refusal offers the video on the platform itself, because that is the way onward that does
// work while this page cannot read it.
interface Refusal {
  status: number;
  title: string;
  lines: (videoId: string) => string[];
}

function watchLink(videoId: string): string {
  const id = escapeHtml(videoId);
  return `You can watch it on the platform:
     <a href="https://www.youtube.com/watch?v=${id}">youtube.com/watch?v=${id}</a>.`;
}

export const REFUSALS: Record<Cause, Refusal> = {
  // The reader did nothing wrong and cannot fix this, so the page says who has to.
  bot_check: {
    status: 502,
    title: "The platform refused this page, not your video",
    lines: (videoId) => [
      `The platform asked this page to prove that it is a person. This page is a server, so it
       cannot.`,
      `Your id is right and the video is fine. ${watchLink(videoId)}`,
      `Trying again will not help. The platform refuses the address this page reads from, and a
       person has to change how this page reaches the platform.`,
    ],
  },
  consent_wall: {
    status: 502,
    title: "The platform asked for consent instead of sending the video",
    lines: (videoId) => [
      `The platform answered with a consent page. It did not send the video.`,
      `Your id is right. ${watchLink(videoId)}`,
      `Trying again is unlikely to help until a person changes how this page asks.`,
    ],
  },
  rate_limited: {
    status: 429,
    title: "The platform is refusing this page for asking too often",
    lines: (videoId) => [
      `The platform limits how often this page can ask it for a video. That limit is reached.`,
      `Nothing was stored. Wait a minute, then try again. ${watchLink(videoId)}`,
    ],
  },
  platform_error: {
    status: 502,
    title: "The platform did not answer",
    lines: (videoId) => [
      `The platform answered with an error. The fault is at the platform, not in the id you gave.`,
      `Nothing was stored. Wait a minute, then try again. ${watchLink(videoId)}`,
    ],
  },
  unrecognised_page: {
    status: 502,
    title: "The platform sent something this page cannot read",
    lines: (videoId) => [
      `The platform answered with a page that carries no video, and it gave no reason.`,
      `The video may be fine. ${watchLink(videoId)}`,
      `Nothing was stored. Trying again is worth doing.`,
    ],
  },
  captions_refused: {
    status: 502,
    title: "The platform refused the caption text",
    lines: (videoId) => [
      `This page found the video and found its caption track. The platform then refused to send the
       text of those captions.`,
      `Your id is right and the video is fine. ${watchLink(videoId)}`,
      `Nothing was stored. Trying again is worth doing.`,
    ],
  },
  captions_not_json: {
    status: 502,
    title: "The platform refused the caption text",
    lines: (videoId) => [
      `This page found the video and asked for its captions. The platform answered with something
       that is not caption text.`,
      `Your id is right and the video is fine. ${watchLink(videoId)}`,
      `Nothing was stored. Trying again is worth doing.`,
    ],
  },
  captions_empty: {
    status: 502,
    title: "The caption track carries no text",
    lines: (videoId) => [
      `This page found a caption track for this video, but the track holds no readable line.`,
      `${watchLink(videoId)}`,
      `Nothing was stored. Trying again is worth doing.`,
    ],
  },
  // A missing video never reaches this map. It is a 404 and it is rendered as one.
  video_missing: {
    status: 404,
    title: "No video with that id",
    lines: (videoId) => [
      `The platform holds no video under <code>${escapeHtml(videoId)}</code>.`,
      `The video may be private, it may be deleted, or the id may have one character wrong.`,
    ],
  },
};

export function renderPage(result: LookupResult): Rendered {
  switch (result.kind) {
    case "ok":
      return result.item.has_captions ? transcriptPage(result.item) : noCaptionsPage(result.item);
    case "bad_id":
      return problemPage(400, "That is not a video id", [
        `A video id is eleven characters, for example <code>gyN9lV9QgyA</code>. This page was given
         <code>${escapeHtml(result.given.slice(0, 40))}</code>, which is not one.`,
        `Take the id from the address of the video. In
         <code>youtube.com/watch?v=gyN9lV9QgyA</code> the id is the part after <code>v=</code>.`,
      ]);
    case "not_found": {
      const missing = REFUSALS.video_missing;
      return problemPage(missing.status, missing.title, missing.lines(result.video_id));
    }
    case "upstream_failed": {
      const refusal = REFUSALS[result.cause];
      return problemPage(refusal.status, refusal.title, refusal.lines(result.video_id));
    }
  }
}

export function renderIndex(): Rendered {
  return {
    status: 200,
    html: document_(`${SITE}: read a video as text`, `<header>
  <p class="eyebrow">${SITE}</p>
  <h1>Read a video as text</h1>
</header>
<div class="note">
  <h2>How it works</h2>
  <p>Give this page a video id and it shows the captions that video already carries, as text you can
  read, search and send to somebody. A transcript is a link.</p>
  <p>The address is <code>/videos?id=&lt;video id&gt;</code>, for example
  <a href="/videos?id=gyN9lV9QgyA">/videos?id=gyN9lV9QgyA</a>.</p>
  <p>Captions only. A video with no captions gets a page that says so.</p>
</div>
<form action="/videos" method="get">
  <label for="id">Video id, eleven characters</label>
  <input type="text" id="id" name="id" inputmode="latin" autocomplete="off"
         placeholder="gyN9lV9QgyA" pattern="[A-Za-z0-9_-]{11}" required>
  <button type="submit">Read it</button>
</form>`),
  };
}

export function renderUnknownRoute(): Rendered {
  return problemPage(404, "There is nothing here", [
    `This page serves one address: <code>/videos?id=&lt;video id&gt;</code>.`,
    `Go to <a href="/">the front page</a> to start from there.`,
  ]);
}
