import { describe, expect, it } from "vitest";
import { SCHEMA_VERSION, type Cause, type LookupResult, type TranscriptItem } from "../contract.js";
import { escapeHtml } from "./escape.js";
import { REFUSALS, paragraphsOf, renderIndex, renderPage, renderUnknownRoute } from "./render.js";

const item = (over: Partial<TranscriptItem> = {}): TranscriptItem => ({
  video_id: "gyN9lV9QgyA",
  schema_version: SCHEMA_VERSION,
  fetched_at: "2026-08-29T12:34:56.000Z",
  title: "A plain title",
  has_captions: true,
  language_code: "en",
  track_kind: "asr",
  track_name: "English (auto-generated)",
  segments: [
    { start_seconds: 0, duration_seconds: 2, text: "the first line" },
    { start_seconds: 2, duration_seconds: 2, text: "the second line" },
  ],
  text: "the first line the second line",
  source: "a source",
  ...over,
});

const ok = (over: Partial<TranscriptItem> = {}): LookupResult => ({
  kind: "ok",
  item: item(over),
  cached: false,
});

describe("escaping", () => {
  it("neutralises every character that can open a tag or close an attribute", () => {
    expect(escapeHtml(`<a href="x" title='y'>&</a>`)).toBe(
      "&lt;a href=&quot;x&quot; title=&#39;y&#39;&gt;&amp;&lt;/a&gt;",
    );
  });

  it("leaves ordinary text alone", () => {
    expect(escapeHtml("a plain sentence")).toBe("a plain sentence");
  });
});

describe("the transcript page", () => {
  it("answers 200 and shows the title and the text", () => {
    const page = renderPage(ok());
    expect(page.status).toBe(200);
    expect(page.html).toContain("A plain title");
    expect(page.html).toContain("the first line the second line");
  });

  it("is a whole document with its style inside it and no second request", () => {
    const { html } = renderPage(ok());
    expect(html.startsWith("<!doctype html>")).toBe(true);
    expect(html).toContain("<style>");
    expect(html).not.toContain("<script");
    expect(html).not.toContain("src=");
    expect(html).not.toContain("stylesheet");
  });

  it("says whether a person or a machine wrote the captions", () => {
    expect(renderPage(ok({ track_kind: "asr" })).html).toContain("generated by machine");
    expect(renderPage(ok({ track_kind: "standard" })).html).toContain("written by a person");
  });

  it("says when the text was read", () => {
    expect(renderPage(ok()).html).toContain("2026-08-29 12:34 UTC");
  });

  it("cannot be made to carry a tag through the title", () => {
    const nasty = "<script>alert(1)</script>";
    const { html } = renderPage(ok({ title: nasty }));
    expect(html).not.toContain(nasty);
    expect(html).not.toContain("<script>alert");
    expect(html).toContain("&lt;script&gt;alert(1)&lt;/script&gt;");
  });

  it("cannot be made to carry a tag through the transcript text", () => {
    const { html } = renderPage(
      ok({ segments: [{ start_seconds: 0, duration_seconds: 1, text: "<img onerror=x>" }] }),
    );
    expect(html).not.toContain("<img onerror");
    expect(html).toContain("&lt;img onerror=x&gt;");
  });

  it("gathers the segments into paragraphs rather than one block", () => {
    const many = Array.from({ length: 60 }, (_, i) => ({
      start_seconds: i,
      duration_seconds: 1,
      text: "a line of about thirty characters",
    }));
    expect(paragraphsOf(item({ segments: many })).length).toBeGreaterThan(1);
  });

  it("still shows the text when the item carries text but no segments", () => {
    expect(paragraphsOf(item({ segments: [], text: "only the joined text" }))).toEqual([
      "only the joined text",
    ]);
  });
});

describe("a video with no captions", () => {
  const silent = ok({ has_captions: false, segments: [], text: "", language_code: "", track_kind: "" });

  it("answers 200, because the video is fine and simply has no text", () => {
    expect(renderPage(silent).status).toBe(200);
  });

  it("says so plainly, and says the page reads captions only", () => {
    const { html } = renderPage(silent);
    expect(html).toContain("This video has no captions");
    expect(html).toContain("does not listen to the audio");
  });

  it("still shows the title of the video", () => {
    expect(renderPage(silent).html).toContain("A plain title");
  });

  it("does not claim a caption track it does not have", () => {
    const { html } = renderPage(silent);
    expect(html).not.toContain("generated by machine");
    expect(html).not.toContain("written by a person");
  });
});

describe("the pages for what went wrong", () => {
  it("answers 400 for a malformed id and shows what a real one looks like", () => {
    const page = renderPage({ kind: "bad_id", given: "nope" });
    expect(page.status).toBe(400);
    expect(page.html).toContain("That is not a video id");
    expect(page.html).toContain("gyN9lV9QgyA");
  });

  it("escapes the malformed id it echoes back", () => {
    const page = renderPage({ kind: "bad_id", given: "<script>alert(1)</script>" });
    expect(page.html).not.toContain("<script>alert");
  });

  it("answers 404 for a video nobody can find", () => {
    const page = renderPage({ kind: "not_found", video_id: "aaaaaaaaaaa" });
    expect(page.status).toBe(404);
    expect(page.html).toContain("No video with that id");
    expect(page.html).toContain("aaaaaaaaaaa");
  });

  it("answers 502 when the platform refused, and says which refusal it was", () => {
    const page = renderPage({
      kind: "upstream_failed",
      video_id: "gyN9lV9QgyA",
      cause: "captions_refused",
      reason: "an empty body",
    });
    expect(page.status).toBe(502);
    expect(page.html).toContain("The platform refused the caption text");
  });

  // A refusal that answered 404 is the defect this page was built on. Nothing in this map may.
  it("answers 404 for a missing video and for nothing else", () => {
    for (const [cause, refusal] of Object.entries(REFUSALS)) {
      expect(refusal.status === 404).toBe(cause === "video_missing");
    }
  });

  it("gives every cause its own page, and never leaves one unrendered", () => {
    for (const cause of Object.keys(REFUSALS) as Cause[]) {
      const page = renderPage({ kind: "upstream_failed", video_id: "gyN9lV9QgyA", cause, reason: "r" });
      expect(page.html).toContain(REFUSALS[cause].title);
      expect(page.status).toBeGreaterThanOrEqual(400);
    }
  });

  it("offers a way onward from every problem page", () => {
    for (const result of [
      { kind: "bad_id", given: "x" },
      { kind: "not_found", video_id: "aaaaaaaaaaa" },
      { kind: "upstream_failed", video_id: "aaaaaaaaaaa", cause: "bot_check", reason: "r" },
    ] satisfies LookupResult[]) {
      expect(renderPage(result).html).toContain('<form action="/videos"');
    }
  });
});

describe("the front page and an address nobody serves", () => {
  it("answers 200 and explains the address", () => {
    const page = renderIndex();
    expect(page.status).toBe(200);
    expect(page.html).toContain("/videos?id=");
    expect(page.html).toContain('<form action="/videos"');
  });

  it("answers 404 for an address this page does not serve", () => {
    const page = renderUnknownRoute();
    expect(page.status).toBe(404);
    expect(page.html).toContain("There is nothing here");
  });
});

describe("the page is usable", () => {
  it("declares the viewport, the language and a colour scheme for both themes", () => {
    const { html } = renderPage(ok());
    expect(html).toContain('<html lang="en">');
    expect(html).toContain("width=device-width");
    expect(html).toContain("color-scheme: light dark");
    expect(html).toContain("prefers-color-scheme: dark");
  });

  it("keeps a visible focus ring, a large tap target and reduced motion", () => {
    const { html } = renderIndex();
    expect(html).toContain(":focus-visible");
    expect(html).toContain("min-height: 44px");
    expect(html).toContain("prefers-reduced-motion");
  });

  it("labels the input rather than leaving it to the placeholder", () => {
    expect(renderIndex().html).toContain('<label for="id"');
  });
});
